CREATE TABLE `FILE_MAPPING` (
  `MAPPING_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FILENAME` varchar(256) NOT NULL,
  `FILEPATH_ID` int(11) NOT NULL,
  `HASH_ID` int(11) NOT NULL,
  `FILE_SEQUENCE` int(11) NOT NULL,
  PRIMARY KEY (`MAPPING_ID`),
  KEY `MAPPING_ID_INDEX` (`MAPPING_ID`),
  KEY `fk_FILE_MAPPING__ID_idx` (`HASH_ID`),
  KEY `fk_FILE_MAPPING_PAT_MAPPING_idx` (`FILEPATH_ID`),
  CONSTRAINT `fk_FILE_MAPPING_PAT_MAPPING` FOREIGN KEY (`FILEPATH_ID`) REFERENCES `PATH_MAPPING` (`PATH_MAPPING_ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `fk_FILE_MAPPING__ID` FOREIGN KEY (`HASH_ID`) REFERENCES `HASH_TABLE` (`HASH_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=985 DEFAULT CHARSET=latin1;


CREATE TABLE `HASH_TABLE` (
  `HASH_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FINGERPRINT` binary(32) DEFAULT NULL,
  PRIMARY KEY (`HASH_ID`),
  UNIQUE KEY `FINGERPRINT_UNIQUE` (`FINGERPRINT`),
  KEY `HASH_ID_INDEX` (`HASH_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=20718 DEFAULT CHARSET=latin1;

CREATE TABLE `PATH_MAPPING` (
  `PATH_MAPPING_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PATHNAME` varchar(4096) NOT NULL,
  `PATHHASH` binary(32) NOT NULL,
  PRIMARY KEY (`PATH_MAPPING_ID`),
  UNIQUE KEY `PATHHASH_UNIQUE` (`PATHHASH`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;


CREATE TABLE `USERS` (
  `USERS_KEY` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45) NOT NULL,
  `FILENAME` varchar(255) NOT NULL,
  `FILE_LOCATION_ID` int(11) NOT NULL,
  PRIMARY KEY (`USERS_KEY`),
  KEY `USERS_KEY_INDEX` (`USERS_KEY`),
  KEY `fk_USERS_PATH_MAPPING_idx` (`FILE_LOCATION_ID`),
  CONSTRAINT `fk_USERS_PATH_MAPPING` FOREIGN KEY (`FILE_LOCATION_ID`) REFERENCES `PATH_MAPPING` (`PATH_MAPPING_ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=985 DEFAULT CHARSET=latin1;

